import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { padding: 20, marginTop: 0, marginBottom: 50, paddingBottom: 100, },
  selectionContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  selectionBox: { flex: 1, marginHorizontal: 5, padding: 20, borderRadius: 12, backgroundColor: '#ffffffcc', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  selectionBoxActive: { backgroundColor: '#2280b0' },
  selectionText: { fontSize: 16, fontWeight: 'bold', color: '#2280b0' },
  selectionTextActive: { color: '#fff' },
  rangeContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  rangeBox: { flex: 1, marginHorizontal: 5, paddingVertical: 10, borderRadius: 8, backgroundColor: '#ffffffcc', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  rangeBoxActive: { backgroundColor: '#2280b0' },
  rangeText: { fontSize: 14, fontWeight: '500', color: '#000000ff' },
  rangeTextActive: { color: '#fff' },
  scanButton: { backgroundColor: '#007bff', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center', marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 3, elevation: 3 },
  scanButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  floatScanButton: {backgroundColor: '#eb2424ff', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center', marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 3, elevation: 3 },
  card: { backgroundColor: '#ffffffcc', borderRadius: 16, padding: 28, marginBottom: 16,  borderWidth: 15, borderColor: '#f5f5f5ff'},
  header: { fontSize: 24, fontWeight: '900', marginTop: 10, color: "black" },
  item: { fontSize: 16, marginVertical: 3 },
  bold: { fontWeight: 'bold' },
  sectionHeader: { fontSize: 22, fontWeight: 'bold', marginTop: 20, marginBottom: 10, textAlign: 'center', color: '#2280b0' },
  noDataText: { fontSize: 14, color: '#999', fontStyle: 'italic', textAlign: 'center', padding: 20 },
  itemRow: {marginBottom: 8, paddingVertical: 6, paddingHorizontal: 4, borderBottomWidth: 0.5, borderColor: '#ccc',},
  nfcButton: {marginTop: 4, backgroundColor: '#007AFF', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8, alignSelf: 'flex-start',},
  nfcButtonText: {color: '#fff',fontSize: 14,fontWeight: '600',},
  button: {padding: 12,backgroundColor: '#007AFF', borderRadius: 8, marginVertical: 10,},
  buttonText: {color: 'white', textAlign: 'center',},
  modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center',},
  modalContent: {width: '80%', backgroundColor: 'white', padding: 20, borderRadius: 12, alignItems: 'center',},
  modalTitle: {fontSize: 18, fontWeight: 'bold', marginBottom: 16,},
  rangeButton: {padding: 12, backgroundColor: '#E0E0E0', borderRadius: 6, marginVertical: 6, width: '100%', alignItems: 'center',},
  cancelButton: {marginTop: 10,},
  cancelText: {color: 'red', fontSize: 16,},
  chartValue: {textAlign: 'center',fontSize: 18,fontWeight: 'bold',marginTop: 10,color: 'black',},
  subheader: {fontSize: 18,fontWeight: '600',marginTop: 15,marginBottom: 5,color: '#555',},
});